id: P64D1D371
initial_creation_type: ocr
source_metadata:
  volumes:
    4f4e74125250434b83fd0fe805c2eb33:
      base_file: v098.txt
      image_group_id: I1PD95943
      title: རྒྱུད་གཞན་གྲུབ་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1825
      volume_number: 98
